name: "Build YCode"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
          - platform: "windows-latest"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup vcpkg
        if: matrix.platform == 'windows-latest'
        run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        run: vcpkg install openssl:x64-windows-static-md

      - name: Set OPENSSL_DIR for Windows
        if: matrix.platform == 'windows-latest'
        run: |
          echo "OPENSSL_DIR=$env:VCPKG_INSTALLATION_ROOT/installed/x64-windows-static-md" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Add MSVC to PATH
        if: matrix.platform == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux DEB
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-deb
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.deb

      - name: Upload Linux RPM
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-rpm
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.rpm

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-appimage
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.AppImage

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-exe
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.exe
